// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAD2InkF8DzEypQkPxk83UUo7_deODDEUc',
    appId: '1:39445181462:android:67e902480c4f94fa27b137',
    messagingSenderId: '39445181462',
    projectId: 'bluewave-9be8f',
    storageBucket: 'bluewave-9be8f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSCQ1wPlCYcqCGN6ZC2EOp3mg8x883DpI',
    appId: '1:39445181462:ios:da84b18e0a5f1b9327b137',
    messagingSenderId: '39445181462',
    projectId: 'bluewave-9be8f',
    storageBucket: 'bluewave-9be8f.appspot.com',
    androidClientId: '39445181462-a33hi8kibkssabkdklpe3pvcvp71giq7.apps.googleusercontent.com',
    iosClientId: '39445181462-ikucjq6eat9g6o9j1gj8gt7en8kkj1a1.apps.googleusercontent.com',
    iosBundleId: 'com.bluewave.app',
  );
}
